#####Read Downloaded existing education file
educ<-read.csv("C:\\Users\\adamg_000\\OneDrive\\Public\\Doing Data Science\\Case1\\education.csv",header=TRUE)
head(educ,10)
#Show the first 10 values
#####Read provided gdp file and skip all rows that do not have relevant data
gdp<-read.csv("C:\\Users\\adamg_000\\OneDrive\\Public\\Doing Data Science\\Case1\\gdp.csv",header=TRUE,skip=5)
#Show first 2 rows of imported data
head(gdp,2)
#Rename the first column to prepare the data for a new header with autogenerated column names
names(gdp)[2]<-1
names(gdp)[4]<-"United States"
names(gdp)[5]<-"16,244,600"
#remove empty column (3)
gdp<-gdp[c(1,2,4,5)]
#create new dataset to prevent correct data from being accidentally broken
gdpb<-gdp
head(gdpb,2)
#Export the data into a CSV file
write.csv(gdpb,file="gdpb.csv")
#Import the new file
gdp<-read.csv("C:\\Users\\adamg_000\\OneDrive\\Public\\Doing Data Science\\Case1\\gdpb.csv",header=FALSE)
head(gdp,2)
#remove the 1st column
gdp<-gdp[c(2,3,4,5)]
head(gdp,2)
#rename the auto generated column names to their original names
names(gdp)[1]<-"CountryCode"
names(gdp)[2]<-"Ranking"
names(gdp)[3]<-"Economy"
names(gdp)[4]<-"MillionsUSD"
head(gdp,2)
#merge the two datasets by the CountryCode
educgdp<-merge(educ,gdp,by="CountryCode")
head(educgdp,2)
#export the merged file as a CSV
write.csv(educgdp,file="educgdp.csv")
#sort the data in decreasing order based on the "Ranking" column
sorttest<-educgdp[order(educgdp$Ranking,decreasing=TRUE),]
head(sorttest,5)
#Export sorted dataset as CSV
write.csv(sorttest,file="sorted.csv")
#read new dataset
sort1<-read.csv("C:\\Users\\adamg_000\\OneDrive\\Public\\Doing Data Science\\Case1\\sorted.csv",header=TRUE)
head(sort1,5)
HighOECD<-sort1[grep("High income: OECD",sort1$Income.Group),]
HighnonOECD<-sort1[grep("High income: nonOECD",sort1$Income.Group),]
HighOECD2<-HighOECD[c(32:35)]
HighnonOECD2<-HighnonOECD[c(32:35)]
####################################
######To ReRun the original code without rewriting csv files
####################################
educ<-read.csv("C:\\Users\\adamg_000\\OneDrive\\Public\\Doing Data Science\\Case1\\education.csv",header=TRUE)
head(educ,10)
gdp<-read.csv("C:\\Users\\adamg_000\\OneDrive\\Public\\Doing Data Science\\Case1\\gdp.csv",header=TRUE,skip=5)
head(gdp,2)
names(gdp)[2]<-1
names(gdp)[4]<-"United States"
names(gdp)[5]<-"16,244,600"
gdp<-gdp[c(1,2,4,5)]
gdpb<-gdp
head(gdpb,2)
gdp<-read.csv("C:\\Users\\adamg_000\\OneDrive\\Public\\Doing Data Science\\Case1\\gdpb.csv",header=FALSE)
head(gdp,2)
gdp<-gdp[c(2,3,4,5)]
head(gdp,2)
names(gdp)[1]<-"CountryCode"
names(gdp)[2]<-"Ranking"
names(gdp)[3]<-"Economy"
names(gdp)[4]<-"MillionsUSD"
head(gdp,2)
educgdp<-merge(educ,gdp,by="CountryCode")
head(educgdp,2)
sorttest<-educgdp[order(educgdp$Ranking,decreasing=TRUE),]
head(sorttest,5)
sort1<-read.csv("C:\\Users\\adamg_000\\OneDrive\\Public\\Doing Data Science\\Case1\\sorted.csv",header=TRUE)
head(sort1,5)
<<<<<<< HEAD
summary(sort1$Income.Group)

=======
HighOECD<-sort1[grep("High income: OECD",sort1$Income.Group),]
HighnonOECD<-sort1[grep("High income: nonOECD",sort1$Income.Group),]
HighOECD2<-HighOECD[c(32:35)]
HighnonOECD2<-HighnonOECD[c(32:35)]
>>>>>>> origin/master
